// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210803161053_updatedSeeding")]
    partial class updatedSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryManagement.Data.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantities")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            Cost = 71.150000000000006,
                            ExpirationDate = new DateTime(2021, 8, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(3228),
                            Manufacturer = "cover",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2021, 7, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(3943),
                            Quantities = 71
                        },
                        new
                        {
                            BatchId = 2,
                            Cost = 66.709999999999994,
                            ExpirationDate = new DateTime(2023, 2, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4303),
                            Manufacturer = "adapt",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2020, 1, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4306),
                            Quantities = 105
                        },
                        new
                        {
                            BatchId = 3,
                            Cost = 93.980000000000004,
                            ExpirationDate = new DateTime(2022, 10, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4308),
                            Manufacturer = "adapt",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2020, 5, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4309),
                            Quantities = 224
                        },
                        new
                        {
                            BatchId = 4,
                            Cost = 68.390000000000001,
                            ExpirationDate = new DateTime(2022, 6, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4333),
                            Manufacturer = "boom",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2020, 9, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4334),
                            Quantities = 464
                        },
                        new
                        {
                            BatchId = 5,
                            Cost = 35.329999999999998,
                            ExpirationDate = new DateTime(2022, 12, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4336),
                            Manufacturer = "during",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2020, 3, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4337),
                            Quantities = 160
                        },
                        new
                        {
                            BatchId = 6,
                            Cost = 75.769999999999996,
                            ExpirationDate = new DateTime(2022, 10, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4344),
                            Manufacturer = "testimony",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2020, 5, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4345),
                            Quantities = 142
                        },
                        new
                        {
                            BatchId = 7,
                            Cost = 54.289999999999999,
                            ExpirationDate = new DateTime(2021, 9, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4351),
                            Manufacturer = "production",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2021, 6, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4352),
                            Quantities = 226
                        },
                        new
                        {
                            BatchId = 8,
                            Cost = 9.8699999999999992,
                            ExpirationDate = new DateTime(2022, 10, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4354),
                            Manufacturer = "dress",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2020, 5, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4355),
                            Quantities = 313
                        },
                        new
                        {
                            BatchId = 9,
                            Cost = 81.959999999999994,
                            ExpirationDate = new DateTime(2022, 6, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4359),
                            Manufacturer = "production",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2020, 9, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4360),
                            Quantities = 339
                        },
                        new
                        {
                            BatchId = 10,
                            Cost = 22.010000000000002,
                            ExpirationDate = new DateTime(2022, 6, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4363),
                            Manufacturer = "contact",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2020, 10, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4364),
                            Quantities = 401
                        },
                        new
                        {
                            BatchId = 11,
                            Cost = 49.689999999999998,
                            ExpirationDate = new DateTime(2022, 12, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4369),
                            Manufacturer = "testimony",
                            ProductId = 4,
                            PurchasedDate = new DateTime(2020, 3, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4370),
                            Quantities = 332
                        },
                        new
                        {
                            BatchId = 12,
                            Cost = 71.939999999999998,
                            ExpirationDate = new DateTime(2022, 5, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4377),
                            Manufacturer = "contact",
                            ProductId = 5,
                            PurchasedDate = new DateTime(2020, 10, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4378),
                            Quantities = 262
                        },
                        new
                        {
                            BatchId = 13,
                            Cost = 52.119999999999997,
                            ExpirationDate = new DateTime(2022, 1, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4380),
                            Manufacturer = "married",
                            ProductId = 5,
                            PurchasedDate = new DateTime(2021, 2, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4381),
                            Quantities = 399
                        },
                        new
                        {
                            BatchId = 14,
                            Cost = 85.260000000000005,
                            ExpirationDate = new DateTime(2022, 7, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4382),
                            Manufacturer = "cast",
                            ProductId = 5,
                            PurchasedDate = new DateTime(2020, 9, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4383),
                            Quantities = 302
                        },
                        new
                        {
                            BatchId = 15,
                            Cost = 26.239999999999998,
                            ExpirationDate = new DateTime(2022, 2, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4385),
                            Manufacturer = "precisely",
                            ProductId = 5,
                            PurchasedDate = new DateTime(2021, 1, 30, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4386),
                            Quantities = 130
                        },
                        new
                        {
                            BatchId = 16,
                            Cost = 84.489999999999995,
                            ExpirationDate = new DateTime(2023, 1, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4387),
                            Manufacturer = "mere",
                            ProductId = 5,
                            PurchasedDate = new DateTime(2020, 2, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4388),
                            Quantities = 183
                        },
                        new
                        {
                            BatchId = 17,
                            Cost = 7.46,
                            ExpirationDate = new DateTime(2023, 3, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4393),
                            Manufacturer = "detect",
                            ProductId = 6,
                            PurchasedDate = new DateTime(2019, 12, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4394),
                            Quantities = 184
                        },
                        new
                        {
                            BatchId = 18,
                            Cost = 69.609999999999999,
                            ExpirationDate = new DateTime(2022, 4, 30, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4396),
                            Manufacturer = "married",
                            ProductId = 6,
                            PurchasedDate = new DateTime(2020, 11, 6, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4397),
                            Quantities = 115
                        },
                        new
                        {
                            BatchId = 19,
                            Cost = 12.07,
                            ExpirationDate = new DateTime(2022, 9, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4406),
                            Manufacturer = "production",
                            ProductId = 8,
                            PurchasedDate = new DateTime(2020, 6, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4407),
                            Quantities = 32
                        },
                        new
                        {
                            BatchId = 20,
                            Cost = 95.790000000000006,
                            ExpirationDate = new DateTime(2021, 9, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4409),
                            Manufacturer = "greatest",
                            ProductId = 8,
                            PurchasedDate = new DateTime(2021, 6, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4410),
                            Quantities = 387
                        },
                        new
                        {
                            BatchId = 21,
                            Cost = 11.17,
                            ExpirationDate = new DateTime(2022, 4, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4411),
                            Manufacturer = "sigh",
                            ProductId = 8,
                            PurchasedDate = new DateTime(2020, 12, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4413),
                            Quantities = 84
                        },
                        new
                        {
                            BatchId = 22,
                            Cost = 52.420000000000002,
                            ExpirationDate = new DateTime(2022, 8, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4414),
                            Manufacturer = "sanction",
                            ProductId = 8,
                            PurchasedDate = new DateTime(2020, 7, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4415),
                            Quantities = 426
                        },
                        new
                        {
                            BatchId = 23,
                            Cost = 12.890000000000001,
                            ExpirationDate = new DateTime(2022, 4, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4421),
                            Manufacturer = "system",
                            ProductId = 9,
                            PurchasedDate = new DateTime(2020, 11, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4422),
                            Quantities = 189
                        },
                        new
                        {
                            BatchId = 24,
                            Cost = 88.290000000000006,
                            ExpirationDate = new DateTime(2021, 10, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4428),
                            Manufacturer = "cast",
                            ProductId = 10,
                            PurchasedDate = new DateTime(2021, 5, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4429),
                            Quantities = 265
                        },
                        new
                        {
                            BatchId = 25,
                            Cost = 27.25,
                            ExpirationDate = new DateTime(2021, 9, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4433),
                            Manufacturer = "post",
                            ProductId = 11,
                            PurchasedDate = new DateTime(2021, 6, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4434),
                            Quantities = 489
                        },
                        new
                        {
                            BatchId = 26,
                            Cost = 59.289999999999999,
                            ExpirationDate = new DateTime(2021, 11, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4436),
                            Manufacturer = "board",
                            ProductId = 11,
                            PurchasedDate = new DateTime(2021, 4, 22, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4437),
                            Quantities = 274
                        },
                        new
                        {
                            BatchId = 27,
                            Cost = 79.209999999999994,
                            ExpirationDate = new DateTime(2023, 5, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4438),
                            Manufacturer = "circumstance",
                            ProductId = 11,
                            PurchasedDate = new DateTime(2019, 10, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4439),
                            Quantities = 452
                        },
                        new
                        {
                            BatchId = 28,
                            Cost = 56.170000000000002,
                            ExpirationDate = new DateTime(2022, 11, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4441),
                            Manufacturer = "egg",
                            ProductId = 11,
                            PurchasedDate = new DateTime(2020, 4, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4442),
                            Quantities = 210
                        },
                        new
                        {
                            BatchId = 29,
                            Cost = 42.880000000000003,
                            ExpirationDate = new DateTime(2022, 11, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4443),
                            Manufacturer = "production",
                            ProductId = 11,
                            PurchasedDate = new DateTime(2020, 5, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4444),
                            Quantities = 232
                        },
                        new
                        {
                            BatchId = 30,
                            Cost = 67.560000000000002,
                            ExpirationDate = new DateTime(2021, 9, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4449),
                            Manufacturer = "ground",
                            ProductId = 12,
                            PurchasedDate = new DateTime(2021, 6, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4450),
                            Quantities = 71
                        },
                        new
                        {
                            BatchId = 31,
                            Cost = 39.130000000000003,
                            ExpirationDate = new DateTime(2022, 3, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4498),
                            Manufacturer = "contact",
                            ProductId = 14,
                            PurchasedDate = new DateTime(2021, 1, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4499),
                            Quantities = 497
                        },
                        new
                        {
                            BatchId = 32,
                            Cost = 37.539999999999999,
                            ExpirationDate = new DateTime(2023, 6, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4507),
                            Manufacturer = "taxpayer",
                            ProductId = 16,
                            PurchasedDate = new DateTime(2019, 9, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4508),
                            Quantities = 355
                        },
                        new
                        {
                            BatchId = 33,
                            Cost = 39.579999999999998,
                            ExpirationDate = new DateTime(2023, 6, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4510),
                            Manufacturer = "board",
                            ProductId = 16,
                            PurchasedDate = new DateTime(2019, 9, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4511),
                            Quantities = 152
                        },
                        new
                        {
                            BatchId = 34,
                            Cost = 27.399999999999999,
                            ExpirationDate = new DateTime(2022, 4, 6, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4523),
                            Manufacturer = "taxpayer",
                            ProductId = 19,
                            PurchasedDate = new DateTime(2020, 11, 30, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4524),
                            Quantities = 384
                        },
                        new
                        {
                            BatchId = 35,
                            Cost = 12.1,
                            ExpirationDate = new DateTime(2022, 10, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4526),
                            Manufacturer = "sanction",
                            ProductId = 19,
                            PurchasedDate = new DateTime(2020, 5, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4527),
                            Quantities = 395
                        },
                        new
                        {
                            BatchId = 36,
                            Cost = 7.1799999999999997,
                            ExpirationDate = new DateTime(2023, 7, 22, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4528),
                            Manufacturer = "mere",
                            ProductId = 19,
                            PurchasedDate = new DateTime(2019, 8, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4529),
                            Quantities = 349
                        },
                        new
                        {
                            BatchId = 37,
                            Cost = 83.810000000000002,
                            ExpirationDate = new DateTime(2023, 4, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4534),
                            Manufacturer = "mere",
                            ProductId = 20,
                            PurchasedDate = new DateTime(2019, 11, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4535),
                            Quantities = 215
                        },
                        new
                        {
                            BatchId = 38,
                            Cost = 61.350000000000001,
                            ExpirationDate = new DateTime(2023, 5, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4537),
                            Manufacturer = "software",
                            ProductId = 20,
                            PurchasedDate = new DateTime(2019, 10, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4538),
                            Quantities = 132
                        },
                        new
                        {
                            BatchId = 39,
                            Cost = 94.950000000000003,
                            ExpirationDate = new DateTime(2022, 1, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4539),
                            Manufacturer = "impress",
                            ProductId = 20,
                            PurchasedDate = new DateTime(2021, 2, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4540),
                            Quantities = 475
                        },
                        new
                        {
                            BatchId = 40,
                            Cost = 43.200000000000003,
                            ExpirationDate = new DateTime(2022, 7, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4544),
                            Manufacturer = "during",
                            ProductId = 21,
                            PurchasedDate = new DateTime(2020, 8, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4545),
                            Quantities = 140
                        },
                        new
                        {
                            BatchId = 41,
                            Cost = 17.059999999999999,
                            ExpirationDate = new DateTime(2022, 8, 15, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4546),
                            Manufacturer = "adapt",
                            ProductId = 21,
                            PurchasedDate = new DateTime(2020, 7, 22, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4547),
                            Quantities = 223
                        },
                        new
                        {
                            BatchId = 42,
                            Cost = 7.8899999999999997,
                            ExpirationDate = new DateTime(2022, 4, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4549),
                            Manufacturer = "comparison",
                            ProductId = 21,
                            PurchasedDate = new DateTime(2020, 11, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4550),
                            Quantities = 135
                        },
                        new
                        {
                            BatchId = 43,
                            Cost = 71.060000000000002,
                            ExpirationDate = new DateTime(2022, 11, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4551),
                            Manufacturer = "cast",
                            ProductId = 21,
                            PurchasedDate = new DateTime(2020, 4, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4552),
                            Quantities = 168
                        },
                        new
                        {
                            BatchId = 44,
                            Cost = 66.819999999999993,
                            ExpirationDate = new DateTime(2023, 6, 6, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4554),
                            Manufacturer = "mere",
                            ProductId = 21,
                            PurchasedDate = new DateTime(2019, 10, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4555),
                            Quantities = 454
                        },
                        new
                        {
                            BatchId = 45,
                            Cost = 81.569999999999993,
                            ExpirationDate = new DateTime(2023, 5, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4559),
                            Manufacturer = "detect",
                            ProductId = 22,
                            PurchasedDate = new DateTime(2019, 10, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4560),
                            Quantities = 10
                        },
                        new
                        {
                            BatchId = 46,
                            Cost = 10.859999999999999,
                            ExpirationDate = new DateTime(2021, 10, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4565),
                            Manufacturer = "during",
                            ProductId = 23,
                            PurchasedDate = new DateTime(2021, 5, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4566),
                            Quantities = 216
                        },
                        new
                        {
                            BatchId = 47,
                            Cost = 46.710000000000001,
                            ExpirationDate = new DateTime(2023, 4, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4567),
                            Manufacturer = "cover",
                            ProductId = 23,
                            PurchasedDate = new DateTime(2019, 11, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4568),
                            Quantities = 367
                        },
                        new
                        {
                            BatchId = 48,
                            Cost = 19.440000000000001,
                            ExpirationDate = new DateTime(2022, 7, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4573),
                            Manufacturer = "taxpayer",
                            ProductId = 24,
                            PurchasedDate = new DateTime(2020, 8, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4574),
                            Quantities = 192
                        },
                        new
                        {
                            BatchId = 49,
                            Cost = 27.420000000000002,
                            ExpirationDate = new DateTime(2023, 4, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4575),
                            Manufacturer = "boom",
                            ProductId = 24,
                            PurchasedDate = new DateTime(2019, 12, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4576),
                            Quantities = 474
                        },
                        new
                        {
                            BatchId = 50,
                            Cost = 99.780000000000001,
                            ExpirationDate = new DateTime(2022, 6, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4578),
                            Manufacturer = "ground",
                            ProductId = 24,
                            PurchasedDate = new DateTime(2020, 9, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4579),
                            Quantities = 46
                        },
                        new
                        {
                            BatchId = 51,
                            Cost = 91.439999999999998,
                            ExpirationDate = new DateTime(2021, 12, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4580),
                            Manufacturer = "expression",
                            ProductId = 24,
                            PurchasedDate = new DateTime(2021, 4, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4581),
                            Quantities = 62
                        },
                        new
                        {
                            BatchId = 52,
                            Cost = 1.0,
                            ExpirationDate = new DateTime(2021, 9, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4593),
                            Manufacturer = "system",
                            ProductId = 28,
                            PurchasedDate = new DateTime(2021, 6, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4594),
                            Quantities = 68
                        },
                        new
                        {
                            BatchId = 53,
                            Cost = 27.68,
                            ExpirationDate = new DateTime(2023, 3, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4596),
                            Manufacturer = "circumstance",
                            ProductId = 28,
                            PurchasedDate = new DateTime(2019, 12, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4597),
                            Quantities = 17
                        },
                        new
                        {
                            BatchId = 54,
                            Cost = 10.41,
                            ExpirationDate = new DateTime(2022, 1, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4598),
                            Manufacturer = "exactly",
                            ProductId = 28,
                            PurchasedDate = new DateTime(2021, 3, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4599),
                            Quantities = 88
                        },
                        new
                        {
                            BatchId = 55,
                            Cost = 50.25,
                            ExpirationDate = new DateTime(2023, 1, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4601),
                            Manufacturer = "egg",
                            ProductId = 28,
                            PurchasedDate = new DateTime(2020, 2, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4602),
                            Quantities = 178
                        },
                        new
                        {
                            BatchId = 56,
                            Cost = 36.439999999999998,
                            ExpirationDate = new DateTime(2023, 3, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4604),
                            Manufacturer = "mark",
                            ProductId = 28,
                            PurchasedDate = new DateTime(2019, 12, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4605),
                            Quantities = 432
                        },
                        new
                        {
                            BatchId = 57,
                            Cost = 27.989999999999998,
                            ExpirationDate = new DateTime(2022, 3, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4610),
                            Manufacturer = "exactly",
                            ProductId = 29,
                            PurchasedDate = new DateTime(2020, 12, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4611),
                            Quantities = 196
                        },
                        new
                        {
                            BatchId = 58,
                            Cost = 84.209999999999994,
                            ExpirationDate = new DateTime(2023, 6, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4612),
                            Manufacturer = "precisely",
                            ProductId = 29,
                            PurchasedDate = new DateTime(2019, 9, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4613),
                            Quantities = 161
                        },
                        new
                        {
                            BatchId = 59,
                            Cost = 30.899999999999999,
                            ExpirationDate = new DateTime(2023, 1, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4615),
                            Manufacturer = "comparison",
                            ProductId = 29,
                            PurchasedDate = new DateTime(2020, 2, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4615),
                            Quantities = 379
                        },
                        new
                        {
                            BatchId = 60,
                            Cost = 40.670000000000002,
                            ExpirationDate = new DateTime(2021, 9, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4617),
                            Manufacturer = "system",
                            ProductId = 29,
                            PurchasedDate = new DateTime(2021, 6, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4618),
                            Quantities = 203
                        },
                        new
                        {
                            BatchId = 61,
                            Cost = 85.810000000000002,
                            ExpirationDate = new DateTime(2022, 7, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4623),
                            Manufacturer = "border",
                            ProductId = 30,
                            PurchasedDate = new DateTime(2020, 8, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4624),
                            Quantities = 202
                        },
                        new
                        {
                            BatchId = 62,
                            Cost = 95.989999999999995,
                            ExpirationDate = new DateTime(2023, 2, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4625),
                            Manufacturer = "precisely",
                            ProductId = 30,
                            PurchasedDate = new DateTime(2020, 1, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4626),
                            Quantities = 102
                        },
                        new
                        {
                            BatchId = 63,
                            Cost = 38.170000000000002,
                            ExpirationDate = new DateTime(2022, 6, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4628),
                            Manufacturer = "board",
                            ProductId = 30,
                            PurchasedDate = new DateTime(2020, 9, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4629),
                            Quantities = 249
                        },
                        new
                        {
                            BatchId = 64,
                            Cost = 68.859999999999999,
                            ExpirationDate = new DateTime(2023, 5, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4630),
                            Manufacturer = "cover",
                            ProductId = 30,
                            PurchasedDate = new DateTime(2019, 10, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4631),
                            Quantities = 235
                        },
                        new
                        {
                            BatchId = 65,
                            Cost = 99.719999999999999,
                            ExpirationDate = new DateTime(2022, 8, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4632),
                            Manufacturer = "expression",
                            ProductId = 30,
                            PurchasedDate = new DateTime(2020, 7, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4633),
                            Quantities = 398
                        },
                        new
                        {
                            BatchId = 66,
                            Cost = 51.159999999999997,
                            ExpirationDate = new DateTime(2022, 12, 31, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4639),
                            Manufacturer = "post",
                            ProductId = 31,
                            PurchasedDate = new DateTime(2020, 3, 6, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4640),
                            Quantities = 393
                        },
                        new
                        {
                            BatchId = 67,
                            Cost = 15.57,
                            ExpirationDate = new DateTime(2022, 6, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4641),
                            Manufacturer = "dress",
                            ProductId = 31,
                            PurchasedDate = new DateTime(2020, 10, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4642),
                            Quantities = 202
                        },
                        new
                        {
                            BatchId = 68,
                            Cost = 91.909999999999997,
                            ExpirationDate = new DateTime(2022, 7, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4644),
                            Manufacturer = "system",
                            ProductId = 31,
                            PurchasedDate = new DateTime(2020, 9, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4645),
                            Quantities = 29
                        },
                        new
                        {
                            BatchId = 69,
                            Cost = 28.640000000000001,
                            ExpirationDate = new DateTime(2022, 3, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4679),
                            Manufacturer = "software",
                            ProductId = 32,
                            PurchasedDate = new DateTime(2021, 1, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4680),
                            Quantities = 494
                        },
                        new
                        {
                            BatchId = 70,
                            Cost = 31.850000000000001,
                            ExpirationDate = new DateTime(2023, 2, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4681),
                            Manufacturer = "mere",
                            ProductId = 32,
                            PurchasedDate = new DateTime(2020, 1, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4682),
                            Quantities = 455
                        },
                        new
                        {
                            BatchId = 71,
                            Cost = 89.519999999999996,
                            ExpirationDate = new DateTime(2022, 11, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4683),
                            Manufacturer = "during",
                            ProductId = 32,
                            PurchasedDate = new DateTime(2020, 4, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4684),
                            Quantities = 114
                        },
                        new
                        {
                            BatchId = 72,
                            Cost = 98.659999999999997,
                            ExpirationDate = new DateTime(2022, 9, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4686),
                            Manufacturer = "exactly",
                            ProductId = 32,
                            PurchasedDate = new DateTime(2020, 7, 3, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4687),
                            Quantities = 187
                        },
                        new
                        {
                            BatchId = 73,
                            Cost = 25.649999999999999,
                            ExpirationDate = new DateTime(2023, 4, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4694),
                            Manufacturer = "during",
                            ProductId = 33,
                            PurchasedDate = new DateTime(2019, 11, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4694),
                            Quantities = 235
                        },
                        new
                        {
                            BatchId = 74,
                            Cost = 60.57,
                            ExpirationDate = new DateTime(2022, 4, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4696),
                            Manufacturer = "suppose",
                            ProductId = 33,
                            PurchasedDate = new DateTime(2020, 11, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4697),
                            Quantities = 98
                        },
                        new
                        {
                            BatchId = 75,
                            Cost = 92.269999999999996,
                            ExpirationDate = new DateTime(2021, 10, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4702),
                            Manufacturer = "circle",
                            ProductId = 34,
                            PurchasedDate = new DateTime(2021, 6, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4703),
                            Quantities = 406
                        },
                        new
                        {
                            BatchId = 76,
                            Cost = 97.560000000000002,
                            ExpirationDate = new DateTime(2021, 11, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4704),
                            Manufacturer = "cover",
                            ProductId = 34,
                            PurchasedDate = new DateTime(2021, 4, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4705),
                            Quantities = 477
                        },
                        new
                        {
                            BatchId = 77,
                            Cost = 58.100000000000001,
                            ExpirationDate = new DateTime(2022, 10, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4707),
                            Manufacturer = "production",
                            ProductId = 34,
                            PurchasedDate = new DateTime(2020, 5, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4707),
                            Quantities = 65
                        },
                        new
                        {
                            BatchId = 78,
                            Cost = 99.590000000000003,
                            ExpirationDate = new DateTime(2022, 11, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4712),
                            Manufacturer = "independence",
                            ProductId = 35,
                            PurchasedDate = new DateTime(2020, 4, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4713),
                            Quantities = 185
                        },
                        new
                        {
                            BatchId = 79,
                            Cost = 40.630000000000003,
                            ExpirationDate = new DateTime(2021, 11, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4718),
                            Manufacturer = "post",
                            ProductId = 36,
                            PurchasedDate = new DateTime(2021, 4, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4719),
                            Quantities = 440
                        },
                        new
                        {
                            BatchId = 80,
                            Cost = 29.629999999999999,
                            ExpirationDate = new DateTime(2021, 12, 29, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4721),
                            Manufacturer = "married",
                            ProductId = 36,
                            PurchasedDate = new DateTime(2021, 3, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4722),
                            Quantities = 356
                        },
                        new
                        {
                            BatchId = 81,
                            Cost = 32.439999999999998,
                            ExpirationDate = new DateTime(2022, 7, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4723),
                            Manufacturer = "comparison",
                            ProductId = 36,
                            PurchasedDate = new DateTime(2020, 8, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4724),
                            Quantities = 414
                        },
                        new
                        {
                            BatchId = 82,
                            Cost = 10.99,
                            ExpirationDate = new DateTime(2022, 10, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4725),
                            Manufacturer = "contact",
                            ProductId = 36,
                            PurchasedDate = new DateTime(2020, 5, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4726),
                            Quantities = 225
                        },
                        new
                        {
                            BatchId = 83,
                            Cost = 69.219999999999999,
                            ExpirationDate = new DateTime(2022, 10, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4728),
                            Manufacturer = "circumstance",
                            ProductId = 36,
                            PurchasedDate = new DateTime(2020, 6, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4729),
                            Quantities = 62
                        },
                        new
                        {
                            BatchId = 84,
                            Cost = 34.350000000000001,
                            ExpirationDate = new DateTime(2021, 12, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4733),
                            Manufacturer = "mere",
                            ProductId = 37,
                            PurchasedDate = new DateTime(2021, 3, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4734),
                            Quantities = 193
                        },
                        new
                        {
                            BatchId = 85,
                            Cost = 99.870000000000005,
                            ExpirationDate = new DateTime(2023, 7, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4736),
                            Manufacturer = "suppose",
                            ProductId = 37,
                            PurchasedDate = new DateTime(2019, 8, 31, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4737),
                            Quantities = 315
                        },
                        new
                        {
                            BatchId = 86,
                            Cost = 96.359999999999999,
                            ExpirationDate = new DateTime(2023, 1, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4738),
                            Manufacturer = "boom",
                            ProductId = 37,
                            PurchasedDate = new DateTime(2020, 2, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4739),
                            Quantities = 435
                        },
                        new
                        {
                            BatchId = 87,
                            Cost = 99.870000000000005,
                            ExpirationDate = new DateTime(2022, 7, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4744),
                            Manufacturer = "during",
                            ProductId = 38,
                            PurchasedDate = new DateTime(2020, 8, 23, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4745),
                            Quantities = 342
                        },
                        new
                        {
                            BatchId = 88,
                            Cost = 72.909999999999997,
                            ExpirationDate = new DateTime(2021, 10, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4749),
                            Manufacturer = "sigh",
                            ProductId = 39,
                            PurchasedDate = new DateTime(2021, 5, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4750),
                            Quantities = 360
                        },
                        new
                        {
                            BatchId = 89,
                            Cost = 24.460000000000001,
                            ExpirationDate = new DateTime(2022, 7, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4752),
                            Manufacturer = "detect",
                            ProductId = 39,
                            PurchasedDate = new DateTime(2020, 8, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4753),
                            Quantities = 477
                        },
                        new
                        {
                            BatchId = 90,
                            Cost = 34.630000000000003,
                            ExpirationDate = new DateTime(2022, 6, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4754),
                            Manufacturer = "egg",
                            ProductId = 39,
                            PurchasedDate = new DateTime(2020, 9, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4755),
                            Quantities = 398
                        },
                        new
                        {
                            BatchId = 91,
                            Cost = 14.699999999999999,
                            ExpirationDate = new DateTime(2021, 11, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4756),
                            Manufacturer = "border",
                            ProductId = 39,
                            PurchasedDate = new DateTime(2021, 4, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4757),
                            Quantities = 183
                        },
                        new
                        {
                            BatchId = 92,
                            Cost = 80.549999999999997,
                            ExpirationDate = new DateTime(2022, 5, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4761),
                            Manufacturer = "post",
                            ProductId = 40,
                            PurchasedDate = new DateTime(2020, 10, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4762),
                            Quantities = 190
                        },
                        new
                        {
                            BatchId = 93,
                            Cost = 29.18,
                            ExpirationDate = new DateTime(2021, 11, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4764),
                            Manufacturer = "expression",
                            ProductId = 40,
                            PurchasedDate = new DateTime(2021, 5, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4765),
                            Quantities = 110
                        },
                        new
                        {
                            BatchId = 94,
                            Cost = 22.91,
                            ExpirationDate = new DateTime(2021, 12, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4767),
                            Manufacturer = "board",
                            ProductId = 40,
                            PurchasedDate = new DateTime(2021, 3, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4767),
                            Quantities = 114
                        },
                        new
                        {
                            BatchId = 95,
                            Cost = 80.260000000000005,
                            ExpirationDate = new DateTime(2022, 4, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4772),
                            Manufacturer = "comparison",
                            ProductId = 41,
                            PurchasedDate = new DateTime(2020, 12, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4773),
                            Quantities = 138
                        },
                        new
                        {
                            BatchId = 96,
                            Cost = 22.34,
                            ExpirationDate = new DateTime(2022, 3, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4774),
                            Manufacturer = "detect",
                            ProductId = 41,
                            PurchasedDate = new DateTime(2020, 12, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4775),
                            Quantities = 356
                        },
                        new
                        {
                            BatchId = 97,
                            Cost = 8.9399999999999995,
                            ExpirationDate = new DateTime(2021, 8, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4777),
                            Manufacturer = "exactly",
                            ProductId = 41,
                            PurchasedDate = new DateTime(2021, 7, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4778),
                            Quantities = 318
                        },
                        new
                        {
                            BatchId = 98,
                            Cost = 72.439999999999998,
                            ExpirationDate = new DateTime(2022, 10, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4779),
                            Manufacturer = "sigh",
                            ProductId = 41,
                            PurchasedDate = new DateTime(2020, 5, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4780),
                            Quantities = 107
                        },
                        new
                        {
                            BatchId = 99,
                            Cost = 85.239999999999995,
                            ExpirationDate = new DateTime(2021, 11, 9, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4784),
                            Manufacturer = "mark",
                            ProductId = 42,
                            PurchasedDate = new DateTime(2021, 4, 27, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4785),
                            Quantities = 168
                        },
                        new
                        {
                            BatchId = 100,
                            Cost = 52.119999999999997,
                            ExpirationDate = new DateTime(2022, 12, 13, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4787),
                            Manufacturer = "border",
                            ProductId = 42,
                            PurchasedDate = new DateTime(2020, 3, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4787),
                            Quantities = 290
                        },
                        new
                        {
                            BatchId = 101,
                            Cost = 17.420000000000002,
                            ExpirationDate = new DateTime(2023, 1, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4789),
                            Manufacturer = "impress",
                            ProductId = 42,
                            PurchasedDate = new DateTime(2020, 3, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4790),
                            Quantities = 206
                        },
                        new
                        {
                            BatchId = 102,
                            Cost = 17.18,
                            ExpirationDate = new DateTime(2022, 9, 24, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4791),
                            Manufacturer = "cover",
                            ProductId = 42,
                            PurchasedDate = new DateTime(2020, 6, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4792),
                            Quantities = 301
                        },
                        new
                        {
                            BatchId = 103,
                            Cost = 2.5099999999999998,
                            ExpirationDate = new DateTime(2023, 7, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4794),
                            Manufacturer = "dress",
                            ProductId = 42,
                            PurchasedDate = new DateTime(2019, 8, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4795),
                            Quantities = 150
                        },
                        new
                        {
                            BatchId = 104,
                            Cost = 17.859999999999999,
                            ExpirationDate = new DateTime(2023, 7, 17, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4799),
                            Manufacturer = "expression",
                            ProductId = 43,
                            PurchasedDate = new DateTime(2019, 8, 21, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4800),
                            Quantities = 243
                        },
                        new
                        {
                            BatchId = 105,
                            Cost = 6.4400000000000004,
                            ExpirationDate = new DateTime(2023, 1, 19, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4802),
                            Manufacturer = "detect",
                            ProductId = 43,
                            PurchasedDate = new DateTime(2020, 2, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4803),
                            Quantities = 432
                        },
                        new
                        {
                            BatchId = 106,
                            Cost = 30.170000000000002,
                            ExpirationDate = new DateTime(2023, 4, 15, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4804),
                            Manufacturer = "independence",
                            ProductId = 43,
                            PurchasedDate = new DateTime(2019, 11, 22, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4805),
                            Quantities = 194
                        },
                        new
                        {
                            BatchId = 107,
                            Cost = 93.439999999999998,
                            ExpirationDate = new DateTime(2021, 10, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4807),
                            Manufacturer = "comparison",
                            ProductId = 43,
                            PurchasedDate = new DateTime(2021, 5, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4808),
                            Quantities = 145
                        },
                        new
                        {
                            BatchId = 108,
                            Cost = 79.829999999999998,
                            ExpirationDate = new DateTime(2022, 2, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4812),
                            Manufacturer = "dress",
                            ProductId = 44,
                            PurchasedDate = new DateTime(2021, 1, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4813),
                            Quantities = 490
                        },
                        new
                        {
                            BatchId = 109,
                            Cost = 37.340000000000003,
                            ExpirationDate = new DateTime(2022, 1, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4818),
                            Manufacturer = "egg",
                            ProductId = 45,
                            PurchasedDate = new DateTime(2021, 2, 16, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4819),
                            Quantities = 70
                        },
                        new
                        {
                            BatchId = 110,
                            Cost = 68.689999999999998,
                            ExpirationDate = new DateTime(2022, 11, 8, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4823),
                            Manufacturer = "greatest",
                            ProductId = 46,
                            PurchasedDate = new DateTime(2020, 4, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4824),
                            Quantities = 486
                        },
                        new
                        {
                            BatchId = 111,
                            Cost = 21.41,
                            ExpirationDate = new DateTime(2022, 12, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4826),
                            Manufacturer = "dress",
                            ProductId = 46,
                            PurchasedDate = new DateTime(2020, 3, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4827),
                            Quantities = 195
                        },
                        new
                        {
                            BatchId = 112,
                            Cost = 75.650000000000006,
                            ExpirationDate = new DateTime(2022, 1, 28, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4828),
                            Manufacturer = "agricultural",
                            ProductId = 46,
                            PurchasedDate = new DateTime(2021, 2, 6, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4829),
                            Quantities = 486
                        },
                        new
                        {
                            BatchId = 113,
                            Cost = 84.510000000000005,
                            ExpirationDate = new DateTime(2021, 9, 22, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4831),
                            Manufacturer = "egg",
                            ProductId = 46,
                            PurchasedDate = new DateTime(2021, 6, 14, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4832),
                            Quantities = 251
                        },
                        new
                        {
                            BatchId = 114,
                            Cost = 79.599999999999994,
                            ExpirationDate = new DateTime(2022, 9, 1, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4833),
                            Manufacturer = "greatest",
                            ProductId = 46,
                            PurchasedDate = new DateTime(2020, 7, 5, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4834),
                            Quantities = 422
                        },
                        new
                        {
                            BatchId = 115,
                            Cost = 20.77,
                            ExpirationDate = new DateTime(2023, 4, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4839),
                            Manufacturer = "precisely",
                            ProductId = 47,
                            PurchasedDate = new DateTime(2019, 11, 11, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4840),
                            Quantities = 314
                        },
                        new
                        {
                            BatchId = 116,
                            Cost = 92.260000000000005,
                            ExpirationDate = new DateTime(2022, 8, 30, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4841),
                            Manufacturer = "adapt",
                            ProductId = 47,
                            PurchasedDate = new DateTime(2020, 7, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4842),
                            Quantities = 473
                        },
                        new
                        {
                            BatchId = 117,
                            Cost = 64.719999999999999,
                            ExpirationDate = new DateTime(2022, 5, 7, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4847),
                            Manufacturer = "expression",
                            ProductId = 48,
                            PurchasedDate = new DateTime(2020, 10, 30, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4847),
                            Quantities = 305
                        },
                        new
                        {
                            BatchId = 118,
                            Cost = 15.44,
                            ExpirationDate = new DateTime(2023, 7, 20, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4852),
                            Manufacturer = "cast",
                            ProductId = 49,
                            PurchasedDate = new DateTime(2019, 8, 18, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4853),
                            Quantities = 392
                        },
                        new
                        {
                            BatchId = 119,
                            Cost = 68.090000000000003,
                            ExpirationDate = new DateTime(2022, 5, 2, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4855),
                            Manufacturer = "ground",
                            ProductId = 49,
                            PurchasedDate = new DateTime(2020, 11, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4856),
                            Quantities = 410
                        },
                        new
                        {
                            BatchId = 120,
                            Cost = 21.84,
                            ExpirationDate = new DateTime(2023, 2, 4, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4857),
                            Manufacturer = "impress",
                            ProductId = 49,
                            PurchasedDate = new DateTime(2020, 1, 31, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4858),
                            Quantities = 33
                        },
                        new
                        {
                            BatchId = 121,
                            Cost = 29.670000000000002,
                            ExpirationDate = new DateTime(2022, 9, 26, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4860),
                            Manufacturer = "sigh",
                            ProductId = 49,
                            PurchasedDate = new DateTime(2020, 6, 10, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4861),
                            Quantities = 332
                        },
                        new
                        {
                            BatchId = 122,
                            Cost = 86.359999999999999,
                            ExpirationDate = new DateTime(2021, 10, 12, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4862),
                            Manufacturer = "circle",
                            ProductId = 49,
                            PurchasedDate = new DateTime(2021, 5, 25, 16, 10, 53, 372, DateTimeKind.Utc).AddTicks(4863),
                            Quantities = 271
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnSale")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "ground",
                            Category = "Other",
                            Location = "A7",
                            Name = "Alice blue clock",
                            OnSale = false,
                            Price = 23.559999999999999
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "board",
                            Category = "Beauty",
                            Location = "A9",
                            Name = "Arylide yellow spoon",
                            OnSale = false,
                            Price = 44.0
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "boom",
                            Category = "Outdoor",
                            Location = "A7",
                            Name = "Alice blue bag",
                            OnSale = true,
                            Price = 47.859999999999999
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "precisely",
                            Category = "Pet",
                            Location = "A4",
                            Name = "Army green video games",
                            OnSale = true,
                            Price = 38.799999999999997
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "wonderful",
                            Category = "Fashion",
                            Location = "A4",
                            Name = "Alice blue perfume",
                            OnSale = false,
                            Price = 8.0999999999999996
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "software",
                            Category = "Other",
                            Location = "A9",
                            Name = "Alizarin crimson radio",
                            OnSale = false,
                            Price = 22.489999999999998
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "circle",
                            Category = "Outdoor",
                            Location = "A0",
                            Name = "Amaranth bed",
                            OnSale = true,
                            Price = 61.100000000000001
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "sanction",
                            Category = "Beauty",
                            Location = "A8",
                            Name = "Army green soap",
                            OnSale = true,
                            Price = 59.859999999999999
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "sanction",
                            Category = "Pet",
                            Location = "A1",
                            Name = "Alizarin crimson tooth picks",
                            OnSale = false,
                            Price = 32.549999999999997
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "system",
                            Category = "Beauty",
                            Location = "A6",
                            Name = "Apple green deodorant",
                            OnSale = false,
                            Price = 62.130000000000003
                        },
                        new
                        {
                            ProductId = 11,
                            Brand = "egg",
                            Category = "Outdoor",
                            Location = "A0",
                            Name = "Antique fuchsia clay pot",
                            OnSale = true,
                            Price = 86.099999999999994
                        },
                        new
                        {
                            ProductId = 12,
                            Brand = "married",
                            Category = "Pet",
                            Location = "A0",
                            Name = "Anti-flash white bow",
                            OnSale = false,
                            Price = 21.059999999999999
                        },
                        new
                        {
                            ProductId = 13,
                            Brand = "software",
                            Category = "Beauty",
                            Location = "A8",
                            Name = "Amethyst wagon",
                            OnSale = true,
                            Price = 16.77
                        },
                        new
                        {
                            ProductId = 14,
                            Brand = "cover",
                            Category = "Beauty",
                            Location = "A2",
                            Name = "Aqua toothbrush",
                            OnSale = false,
                            Price = 61.549999999999997
                        },
                        new
                        {
                            ProductId = 15,
                            Brand = "system",
                            Category = "Home",
                            Location = "A8",
                            Name = "Alice blue street lights",
                            OnSale = false,
                            Price = 39.32
                        },
                        new
                        {
                            ProductId = 16,
                            Brand = "egg",
                            Category = "Fashion",
                            Location = "A7",
                            Name = "Amber sharpie",
                            OnSale = true,
                            Price = 32.979999999999997
                        },
                        new
                        {
                            ProductId = 17,
                            Brand = "suppose",
                            Category = "Beauty",
                            Location = "A2",
                            Name = "Arylide yellow street lights",
                            OnSale = true,
                            Price = 71.760000000000005
                        },
                        new
                        {
                            ProductId = 18,
                            Brand = "suppose",
                            Category = "Beauty",
                            Location = "A4",
                            Name = "Apple green canvas",
                            OnSale = true,
                            Price = 59.600000000000001
                        },
                        new
                        {
                            ProductId = 19,
                            Brand = "contact",
                            Category = "Other",
                            Location = "A4",
                            Name = "Arylide yellow bed",
                            OnSale = true,
                            Price = 49.270000000000003
                        },
                        new
                        {
                            ProductId = 20,
                            Brand = "impress",
                            Category = "Other",
                            Location = "A7",
                            Name = "Android Green bed",
                            OnSale = false,
                            Price = 80.989999999999995
                        },
                        new
                        {
                            ProductId = 21,
                            Brand = "cast",
                            Category = "Beauty",
                            Location = "A1",
                            Name = "Asparagus apple",
                            OnSale = false,
                            Price = 72.219999999999999
                        },
                        new
                        {
                            ProductId = 22,
                            Brand = "border",
                            Category = "Electronics",
                            Location = "A0",
                            Name = "Aqua pants",
                            OnSale = true,
                            Price = 65.510000000000005
                        },
                        new
                        {
                            ProductId = 23,
                            Brand = "production",
                            Category = "Electronics",
                            Location = "A5",
                            Name = "Air Force blue purse",
                            OnSale = true,
                            Price = 4.04
                        },
                        new
                        {
                            ProductId = 24,
                            Brand = "adapt",
                            Category = "Fashion",
                            Location = "A0",
                            Name = "Apricot model car",
                            OnSale = true,
                            Price = 99.25
                        },
                        new
                        {
                            ProductId = 25,
                            Brand = "testimony",
                            Category = "Fashion",
                            Location = "A7",
                            Name = "Antique fuchsia mouse pad",
                            OnSale = false,
                            Price = 19.23
                        },
                        new
                        {
                            ProductId = 26,
                            Brand = "comparison",
                            Category = "Pet",
                            Location = "A9",
                            Name = "Army green clay pot",
                            OnSale = false,
                            Price = 19.649999999999999
                        },
                        new
                        {
                            ProductId = 27,
                            Brand = "sigh",
                            Category = "Electronics",
                            Location = "A6",
                            Name = "Apricot street lights",
                            OnSale = true,
                            Price = 34.409999999999997
                        },
                        new
                        {
                            ProductId = 28,
                            Brand = "post",
                            Category = "Electronics",
                            Location = "A7",
                            Name = "Aqua radio",
                            OnSale = false,
                            Price = 77.040000000000006
                        },
                        new
                        {
                            ProductId = 29,
                            Brand = "mere",
                            Category = "Fashion",
                            Location = "A8",
                            Name = "Antique white bow",
                            OnSale = true,
                            Price = 29.649999999999999
                        },
                        new
                        {
                            ProductId = 30,
                            Brand = "cover",
                            Category = "Electronics",
                            Location = "A8",
                            Name = "Amber tooth picks",
                            OnSale = true,
                            Price = 98.290000000000006
                        },
                        new
                        {
                            ProductId = 31,
                            Brand = "agricultural",
                            Category = "Pet",
                            Location = "A6",
                            Name = "Arylide yellow mouse pad",
                            OnSale = true,
                            Price = 13.630000000000001
                        },
                        new
                        {
                            ProductId = 32,
                            Brand = "border",
                            Category = "Beauty",
                            Location = "A5",
                            Name = "Air Force blue canvas",
                            OnSale = true,
                            Price = 61.049999999999997
                        },
                        new
                        {
                            ProductId = 33,
                            Brand = "greatest",
                            Category = "Other",
                            Location = "A4",
                            Name = "American rose bow",
                            OnSale = true,
                            Price = 87.340000000000003
                        },
                        new
                        {
                            ProductId = 34,
                            Brand = "suppose",
                            Category = "Electronics",
                            Location = "A7",
                            Name = "Antique fuchsia wagon",
                            OnSale = true,
                            Price = 96.760000000000005
                        },
                        new
                        {
                            ProductId = 35,
                            Brand = "greatest",
                            Category = "Electronics",
                            Location = "A1",
                            Name = "Air Force blue mouse pad",
                            OnSale = true,
                            Price = 13.210000000000001
                        },
                        new
                        {
                            ProductId = 36,
                            Brand = "agricultural",
                            Category = "Outdoor",
                            Location = "A5",
                            Name = "Alice blue street lights",
                            OnSale = false,
                            Price = 59.119999999999997
                        },
                        new
                        {
                            ProductId = 37,
                            Brand = "wonderful",
                            Category = "Pet",
                            Location = "A7",
                            Name = "Army green door",
                            OnSale = true,
                            Price = 38.450000000000003
                        },
                        new
                        {
                            ProductId = 38,
                            Brand = "mark",
                            Category = "Pet",
                            Location = "A8",
                            Name = "Alice blue tooth picks",
                            OnSale = true,
                            Price = 66.609999999999999
                        },
                        new
                        {
                            ProductId = 39,
                            Brand = "post",
                            Category = "Pet",
                            Location = "A7",
                            Name = "Air Force blue rug",
                            OnSale = true,
                            Price = 47.780000000000001
                        },
                        new
                        {
                            ProductId = 40,
                            Brand = "circumstance",
                            Category = "Pet",
                            Location = "A0",
                            Name = "Apple green bag",
                            OnSale = false,
                            Price = 3.1099999999999999
                        },
                        new
                        {
                            ProductId = 41,
                            Brand = "boom",
                            Category = "Other",
                            Location = "A0",
                            Name = "Antique fuchsia radio",
                            OnSale = true,
                            Price = 72.010000000000005
                        },
                        new
                        {
                            ProductId = 42,
                            Brand = "mark",
                            Category = "Electronics",
                            Location = "A2",
                            Name = "Antique fuchsia candy wrapper",
                            OnSale = true,
                            Price = 74.530000000000001
                        },
                        new
                        {
                            ProductId = 43,
                            Brand = "adapt",
                            Category = "Fashion",
                            Location = "A7",
                            Name = "Asparagus street lights",
                            OnSale = true,
                            Price = 57.619999999999997
                        },
                        new
                        {
                            ProductId = 44,
                            Brand = "system",
                            Category = "Fashion",
                            Location = "A5",
                            Name = "Antique white bag",
                            OnSale = false,
                            Price = 60.899999999999999
                        },
                        new
                        {
                            ProductId = 45,
                            Brand = "mark",
                            Category = "Electronics",
                            Location = "A4",
                            Name = "Apple green clay pot",
                            OnSale = true,
                            Price = 12.59
                        },
                        new
                        {
                            ProductId = 46,
                            Brand = "dress",
                            Category = "Pet",
                            Location = "A6",
                            Name = "Asparagus canvas",
                            OnSale = false,
                            Price = 17.859999999999999
                        },
                        new
                        {
                            ProductId = 47,
                            Brand = "detect",
                            Category = "Pet",
                            Location = "A9",
                            Name = "Amber mouse pad",
                            OnSale = false,
                            Price = 69.650000000000006
                        },
                        new
                        {
                            ProductId = 48,
                            Brand = "agricultural",
                            Category = "Pet",
                            Location = "A2",
                            Name = "Antique fuchsia street lights",
                            OnSale = true,
                            Price = 45.259999999999998
                        },
                        new
                        {
                            ProductId = 49,
                            Brand = "contact",
                            Category = "Home",
                            Location = "A1",
                            Name = "Aquamarine wagon",
                            OnSale = false,
                            Price = 82.370000000000005
                        },
                        new
                        {
                            ProductId = 50,
                            Brand = "system",
                            Category = "Outdoor",
                            Location = "A6",
                            Name = "Almond eraser",
                            OnSale = false,
                            Price = 71.879999999999995
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Batch", b =>
                {
                    b.HasOne("InventoryManagement.Data.Entities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
