// <auto-generated />
using System;
using InventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventoryManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210722190118_addMoreProductsANDBatches")]
    partial class addMoreProductsANDBatches
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryManagement.Data.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantities")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            Cost = 9.0,
                            ExpirationDate = new DateTime(2022, 2, 7, 13, 1, 17, 457, DateTimeKind.Local).AddTicks(7826),
                            Manufacturer = "M1",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(3891),
                            Quantities = 500
                        },
                        new
                        {
                            BatchId = 2,
                            Cost = 8.0,
                            ExpirationDate = new DateTime(2022, 8, 26, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4600),
                            Manufacturer = "M1",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4615),
                            Quantities = 20
                        },
                        new
                        {
                            BatchId = 3,
                            Cost = 7.0,
                            ExpirationDate = new DateTime(2021, 10, 30, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4619),
                            Manufacturer = "M1",
                            ProductId = 1,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4621),
                            Quantities = 50
                        },
                        new
                        {
                            BatchId = 4,
                            Cost = 9.0,
                            ExpirationDate = new DateTime(2022, 2, 7, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4624),
                            Manufacturer = "E1 Inc.",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4627),
                            Quantities = 533
                        },
                        new
                        {
                            BatchId = 5,
                            Cost = 18.0,
                            ExpirationDate = new DateTime(2022, 8, 26, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4630),
                            Manufacturer = "E1 Inc.",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4632),
                            Quantities = 66
                        },
                        new
                        {
                            BatchId = 6,
                            Cost = 759.5,
                            ExpirationDate = new DateTime(2021, 10, 30, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4635),
                            Manufacturer = "E1 Inc.",
                            ProductId = 2,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4637),
                            Quantities = 80
                        },
                        new
                        {
                            BatchId = 7,
                            Cost = 22.030000000000001,
                            ExpirationDate = new DateTime(2022, 2, 7, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4640),
                            Manufacturer = "Bottle Inc",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4642),
                            Quantities = 500
                        },
                        new
                        {
                            BatchId = 8,
                            Cost = 29.879999999999999,
                            ExpirationDate = new DateTime(2022, 8, 26, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4644),
                            Manufacturer = "Bottle Inc",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4647),
                            Quantities = 20
                        },
                        new
                        {
                            BatchId = 9,
                            Cost = 18.550000000000001,
                            ExpirationDate = new DateTime(2021, 10, 30, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4649),
                            Manufacturer = "Bottle Inc",
                            ProductId = 3,
                            PurchasedDate = new DateTime(2021, 7, 22, 13, 1, 17, 466, DateTimeKind.Local).AddTicks(4652),
                            Quantities = 50
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnSale")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "BrandA",
                            Category = "Fashion",
                            Location = "A8",
                            Name = "Product A",
                            OnSale = true,
                            Price = 9.0
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "BrandB",
                            Category = "Electronics",
                            Location = "A2",
                            Name = "Electronics Example Product",
                            OnSale = false,
                            Price = 99.980000000000004
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "BrandC",
                            Category = "Home",
                            Location = "C8",
                            Name = "Water Bottle",
                            OnSale = true,
                            Price = 25.98
                        });
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Batch", b =>
                {
                    b.HasOne("InventoryManagement.Data.Entities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagement.Data.Entities.Product", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
